kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-object-detection
  namespace: object-detection
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: object-detection
data:
  AWS_ACCESS_KEY_ID: =
  AWS_DEFAULT_REGION: dXMtZWFzdC0x
  AWS_S3_BUCKET: =
  AWS_S3_ENDPOINT: aHR0cHM6Ly9zMy51cy1lYXN0LTEuYW1hem9uYXdzLmNvbQ==
  AWS_SECRET_ACCESS_KEY: ==
type: Opaque

